import { mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { Marked } from 'marked'
import { markedHighlight } from 'marked-highlight'
import markedKatex from 'marked-katex-extension'
import Prism from 'prismjs'
// Demo markdown files only use ```javascript and ```mermaid fences. Add more
// grammars here as demos grow; keep the list minimal so the build script stays
// fast and the generated HTML doesn't reference non-existent classes.
import 'prismjs/components/prism-javascript.js'

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)
const PROJECT_ROOT = resolve(__dirname, '..')
const MARKDOWN_DIR = join(PROJECT_ROOT, 'src/markdowns')
const THEMES_DIR = join(PROJECT_ROOT, 'src/themes')
const OUT_DIR = join(PROJECT_ROOT, 'src/generated')
const OUT_FILE = join(OUT_DIR, 'markdown-html.ts')
const THEME_OUT_FILE = join(OUT_DIR, 'theme-css.ts')

// Themes baked as string constants so themeColor.ts can switch them at runtime.
const THEME_SOURCES: Record<string, string> = {
  dark: 'dark.theme.css',
  graphite: 'graphite.theme.css',
  materialDark: 'material-dark.theme.css',
  oneDark: 'one-dark.theme.css',
  ulysses: 'ulysses.theme.css',
  darkPrism: 'prismjs/dark.theme.css',
  oneDarkPrism: 'prismjs/one-dark.theme.css'
}

const MERMAID_HEAD =
  /^(sequenceDiagram|flowchart|graph|gantt|classDiagram|stateDiagram|journey|gitGraph|pie|erDiagram|mindmap|requirementDiagram|quadrantChart|timeline|sankey-beta|xychart-beta|block-beta|architecture-beta|packet-beta|kanban|info)\b/

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;')
}

const marked = new Marked(
  markedHighlight({
    langPrefix: 'language-',
    highlight(code, lang) {
      if (lang === 'mermaid') {
        // Defer rewrap to a post-pass so we can carry the raw source through to
        // the final <div class="mermaid"> as a data-source attribute.
        return `__MERMAID_BLOCK__${Buffer.from(code, 'utf-8').toString('base64')}__END__`
      }
      const grammar = lang && Prism.languages[lang]
      return grammar ? Prism.highlight(code, grammar, lang) : escapeHtml(code)
    }
  }),
  markedKatex({ throwOnError: false })
)
marked.setOptions({ gfm: true, breaks: false })

function mermaidDiv(source: string): string {
  // data-source carries the raw diagram text so Theme.tsx can restore it when
  // the user switches themes — mermaid.run() replaces .textContent with an
  // <svg> after the first render, losing the source otherwise.
  const trimmed = source.trim()
  const escaped = escapeHtml(trimmed)
  return `<div class="mermaid" data-source="${escaped}">${escaped}</div>`
}

function rewrapMermaid(html: string): string {
  return html.replace(
    /<pre><code class="language-mermaid">__MERMAID_BLOCK__([A-Za-z0-9+/=]+)__END__\s*<\/code><\/pre>/g,
    (_, b64) => mermaidDiv(Buffer.from(b64, 'base64').toString('utf-8'))
  )
}

function detectFallbackMermaid(html: string): string {
  // Safety net for the original Vite logic: if a plain <pre><code> happens to
  // contain a Mermaid diagram header, rewrap it the same way.
  if (!html.includes('<pre><code>')) return html
  return html.replace(/<pre><code>([\s\S]*?)<\/code><\/pre>/g, (full, body: string) => {
    const text = body
      .replace(/&lt;/g, '<')
      .replace(/&gt;/g, '>')
      .replace(/&amp;/g, '&')
      .replace(/&quot;/g, '"')
      .replace(/&#39;/g, "'")
      .trim()
    return MERMAID_HEAD.test(text) ? mermaidDiv(text) : full
  })
}

async function renderOne(source: string): Promise<string> {
  const html = await marked.parse(source)
  return detectFallbackMermaid(rewrapMermaid(html))
}

async function main() {
  const entries = readdirSync(MARKDOWN_DIR)
    .filter((f) => f.endsWith('.md'))
    .sort()

  const records: Array<[string, string]> = []
  for (const file of entries) {
    const key = file.replace(/\.md$/, '')
    const source = readFileSync(join(MARKDOWN_DIR, file), 'utf-8')
    const html = await renderOne(source)
    records.push([key, html])
    process.stdout.write(`  prerendered ${file} -> ${html.length} bytes\n`)
  }

  mkdirSync(OUT_DIR, { recursive: true })

  const banner =
    '// AUTO-GENERATED by scripts/prerender-markdown.ts — do not edit by hand.\n' +
    '// Regenerate via `pnpm --filter marktext-website run prebuild`.\n\n'
  const body =
    'export const markdownHtml: Record<string, string> = {\n' +
    records.map(([k, v]) => `  ${JSON.stringify(k)}: ${JSON.stringify(v)}`).join(',\n') +
    '\n}\n\n' +
    'export type MarkdownKey = keyof typeof markdownHtml\n'

  writeFileSync(OUT_FILE, banner + body, 'utf-8')
  process.stdout.write(`Wrote ${OUT_FILE}\n`)

  // Bake theme CSS files into a TS module so themeColor.ts has no `?inline` imports.
  const themeEntries = Object.entries(THEME_SOURCES).map(([name, path]) => {
    const css = readFileSync(join(THEMES_DIR, path), 'utf-8')
    return `export const ${name} = ${JSON.stringify(css)}\n`
  })
  const themeBanner =
    '// AUTO-GENERATED by scripts/prerender-markdown.ts — do not edit by hand.\n\n'
  writeFileSync(THEME_OUT_FILE, themeBanner + themeEntries.join(''), 'utf-8')
  process.stdout.write(`Wrote ${THEME_OUT_FILE}\n`)
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
